name: cloud_helper
description: A new Flutter plugin project.
version: 1.0.0
homepage: https://github.com/Progressive-Mobile/status_stepper

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
  plugin:
    platforms:
      ios:
        pluginClass: CloudHelperPlugin
      macos:
        pluginClass: CloudHelperPlugin
